server:
  port: 10086
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/data/mock_recorder/database.db
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  file: /data/mock_recorder/log.log
  level:
    root: info